### PR TITLE
Firefox support, better theme support, new dark theme

### PR DESCRIPTION
**Pull request by PxlBuzzard**
@ColdenCullen and I spent the weekend at [PennApps X](http://2014f.pennapps.com/) hacking on HN Special, primarily with the intention of bringing it to Firefox. Since then I have continued to bring our changes back to Chrome and improve the theme functionality. While I wouldn't call this work perfect, I think it is good enough to put into a pull request and get feedback.

If you would like to run this in Chrome or Firefox, check out the [Releases](https://github.com/PxlBuzzard/hn-special/releases) in my branch to download the extensions.

### Features

* Firefox (>38) support!
* A new dark theme!
* Themes have been broken apart so that a new theme can be added in [stylus](https://learnboost.github.io/stylus/) by just modifying color variables.
* Theme loading now happens in the page head. This minimizes the number of files being loaded to one instead of all themes, as well as properly filling in the developer console with the CSS rules.

### Known Issues

* No icon in the Firefox extension list. There is a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1141839) for adding relative URIs, and a fix in the meantime would be to include `icon.png` and `icon64.png` in a `/data` directory.
* Mark as read is broken in Firefox.

Issues that will be closed by this PR:  #33 #36 #43 #51 #62

### CODE REVIEW

**Comment by PxlBuzzard** [comment]
Ping @gabrielecirulli again.

I know you must stay busy (I certainly have been), but seeing that this is mostly being left alone on your end I suggest bringing on another couple contributors who can more readily do code reviews and accept changes.

**Comment by extesy** [comment]
+1 for allowing external contributors to this repo

**Comment by gabrielecirulli** [comment]
My apologies for the long delay, I have a hard time tracking what's happening in the projects. I certainly didn't mean to leave this hanging for so long, so I'm sorry for that. I'll review it as soon as I can, hopefully this weekend.

**Comment by derhuerst** [comment]
another ping @gabrielecirulli. would really like to see this as well (:

**Comment by extesy** [comment]
@gabrielecirulli Do you mind transferring ownership of this repository and chrome extension to me? I will at least react on time and accept pull requests.

**Comment by PxlBuzzard** [comment]
As I've stated via email to @gabrielecirulli, I would be happy to help out as well. I don't think he needs to go so far as to transfer ownership, just adding project collaborators would be sufficient. I don't know how ownership works for Chrome and Firefox addons though.

**Comment by PxlBuzzard** [comment]
Followup on addon ownership: 

* Firefox allows multiple owners for a single addon. Problem solved. @gabrielecirulli Would you mind if uploaded it to [Firefox Addons](https://addons.mozilla.org/en-US/firefox/) and made you an owner?
* Chrome allows you to [transfer ownership](https://support.google.com/chrome_webstore/contact/dev_account_transfer). That becomes tricky on the Chrome side: we would probably need a shared email account which is not ideal, but it may be the only way to handle it.

**Comment by gabrielecirulli** [comment]
Some good news: I decided to get off my ass and go back to working on hn special. I've been getting infinite scrolling to work again this afternoon (haven't committed that yet) and I'll work on merging this patch tomorrow. Again, I'm so sorry for letting this sit here since October. I know how irritating it can be. 

I'm also super open for taking a collaborator on board like I did for 2048, so if anyone's up for it (I saw someone asking already), we can talk about it.

**Comment by PxlBuzzard** [comment]
@gabrielecirulli, I've updated the PR to include the latest changes from upstream. I also addressed code review comments from @slang800 (thank you for looking it over).

**Comment by PxlBuzzard** [comment]
@gabrielecirulli I suppose it's as good a time as any to ping this PR again and see if you would like to merge it. I've been using this version of the extension for the last year and a half with no problems.

**Comment by extesy** [comment]
@PxlBuzzard Are you willing to take over the maintenance of this extension? If yes, then you can fork it and upload to chrome webstore yourself. I'll use your fork since this one has been dead for more than a year.

**Comment by PxlBuzzard** [comment]
@extesy I've asked for collaborator access from Gabriele a couple times since I made this PR. I would prefer to keep this repo as the source of truth, but given the recent developments in Firefox with signed extensions it would be best to get it added to the Firefox Addons officially. Chrome is a different beast since the extension already exists in the Webstore, and again I would prefer to avoid "competing" extensions if possible. Hopefully I can get a response by this weekend and I can take some action.

**Comment by gabrielecirulli** [comment]
I can probably give you collaborator access, yes. It doesn't seem like I can go back to this any time soon. Will do that tomorrow morning. Do you have an email address I could reach you at?

**Comment by PxlBuzzard** [comment]
@gabrielecirulli daniel [at] danieljost.com will work fine. Thanks!

**Comment by slang800** [comment]
btw: I ended up forking this PR into a separate hn-special addon for Firefox: https://github.com/slang800/hn-special (using the built-in firefox settings page and removing all the chrome-specific stuff)

**Comment by gabrielecirulli** [comment]
@PxlBuzzard You're now a contributor. Please check your email when you have time 😄

**Comment by FichteFoll** [comment]
Nice!

There hasn't been a new release yet though, has it?

**Comment by PxlBuzzard** [comment]
@FichteFoll I'm hoping to get the new version approved and distributed through official channels, but in the meantime I'll tag and release a new build on Github.

**Pull request merged**
