### PR TITLE
fixed HN folding comments to work with Chrome

### PR DESCRIPTION
**Pull request by dudevon**
fixed issue with https://github.com/gabrielecirulli/hn-special/issues/73

### CODE REVIEW

**Comment by MrAlexWeber** [comment]
I implemented this change myself, locally. While it does fix the appearance of the fold/unfold link, it doesn't fold the comment _thread_, rather just the _individual_ comment.

Here's the error I got: 
 > Uncaught TypeError: comment.getElementsByTagName is not a function    fold_comments.js:69

**Comment by unformatt** [comment]
There's a another nextSibling that needs to be replaced on line 39:

`39:     while (current = current.nextSibling) {`

**Comment by dudevon** [comment]
Thanks for the heads up. I've made the change to the pull request.

**Comment by gabrielecirulli** [comment]
Thank you, I fixed it the same way without noticing there's a pull request for it. Should behave correctly now.

**Pull request closed without merging**
